server:
  port: ${sealtalk-config.server_port}
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:             #解决中文乱码问题，同一使用UTF-8编码
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true

spring:

  flyway:
    enabled: true
    # 禁止清理数据库表
    clean-disabled: true
    baseline-description: baselines
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    baseline-version: 2

  swagger2:
    enabled: false
mybatis:
  mapper-locations: classpath:mybatis/*.xml

logging:
  config: classpath:logback-config.xml


sealtalk:
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://${sealtalk-config.db_host}:${sealtalk-config.db_port}/${sealtalk-config.db_name}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&useCompress=true
    username: ${sealtalk-config.db_user}
    password: ${sealtalk-config.db_password}
    maximum-pool-size: 20

  #sealtalk-config:
  #  auth_cookie_name: '<-- 此处设置 Cookie 名称 -->'
  #  auth_cookie_key: '<-- 此处设置 Cookie 加密密钥 -->'
  #  auth_cookie_max_age: 8640000
  #  rongcloud_sms_register_template_id: 3910922
  #  config_env: dev    # dev 调试环境， 注册环节不发短信，默认验证码9999
  #  rongcloud_app_key: '<-- 此处填写融云颁发的 App Key -->'
  #  rongcloud_app_secret: '<-- 此处填写融云颁发的 App Secret -->'
  #  rongcloud_api_url: '<-- 此处填写融云 Api Url -->'
  #  rongcloud_default_portrait_url: '<-- 此处填写默认头像地址 -->'
  #  qiniu_access_key: '<-- 此处填写七牛颁发的 Access Key -->'
  #  qiniu_secret_key: '<-- 此处填写七牛颁发的 Secret Key -->'
  #  qiniu_bucket_name: '<-- 此处填写七牛创建的空间名称 -->'
  #  qiniu_bucket_domain: '<-- 此处填写七牛创建的空间域名 -->'
  #  yunpian_api_key: '<-- 此处填写云片颁发的 API Key -->'
  #  yunpian_limited_time: 1
  #  yunpian_limited_count: 20
  #  n3d_key: '<-- 此处设置加密 Id 的密钥 -->'
  #  auth_cookie_domain: '<-- 此处设置 Cookie 主域名， 必须和 CORS_HOSTS 配置项在相同的顶级域下 例如： api.sealtalk.im -->'
  #  cors_hosts: '<-- 此处设置请求的域名信息 , 例如： web.sealtalk.im -->'
  #  exclude_url: /misc/demo_square,/misc/latest_update, /user/verify_code_yp_t,/misc/client_version,/misc/mobile_version,/user/login,/user/register,/user/reset_password, /user/send_code, /user/send_code_yp,/user/verify_code, /user/verify_code_yp, /user/delete, /user/get_sms_img_code,/user/check_username_available,/user/check_phone_available,/user/regionlist,/ping
  #  server_port: '<-- 此处设置应用服务监听端口 -->'
  #  db_name: '<-- 此处设置数据库名称 -->'
  #  db_user: '<-- 此处设置数据库用户名 -->'
  #  db_password: '<-- 此处设置数据库密码 -->'
  #  db_host: '<-- 此处设置数据库服务器的 IP 地址 -->'
  #  db_port: '<-- 此处设置数据库服务器的端口号 -->'




  ## 示例：
#  sealtalk-config:
#    auth_cookie_name: rong_auth_cookie
#    auth_cookie_key: zsyy
#    auth_cookie_max_age: 8640000
#    rongcloud_sms_register_template_id: 3910922
#    config_env: dev    # dev 注册环节不发短信，默认验证码9999
#    rongcloud_app_key: bmdehs6apbauls
#    rongcloud_app_secret: xvQhSJbgYBtwF
#    rongcloud_api_url: api-sg01.ronghub.com
#    rongcloud_default_portrait_url: http://download.hotchatvip.com/default_hotchat_avatar.png
#    qiniu_access_key: ctk1VIyQlx5CFr_EQMqrQkF5c1PKGuqC2SNTR749
#    qiniu_secret_key: MRuJJ6AcBkaFQrgm16ayDtv_4L0M2jsQe-QuMBfiw
#    qiniu_bucket_name: devtalk-image
#    qiniu_bucket_domain: self.domain.com
#    yunpian_api_key: 830c361ecb0ef1667e02769e1f33d9942
#    yunpian_limited_time: 1
#    yunpian_limited_count: 20
#    n3d_key: 11EdDIsqpcim
#    auth_cookie_domain: devtalk.im
#    cors_hosts: http://web.devtalk.im
#    # 默认配置不需要修改
#    exclude_url: /misc/demo_square,/misc/latest_update, /user/verify_code_yp_t,/misc/client_version,/misc/mobile_version,/user/login,/user/register,/user/reset_password, /user/send_code, /user/send_code_yp,/user/verify_code, /user/verify_code_yp, /user/delete, /user/get_sms_img_code,/user/check_username_available,/user/check_phone_available,/user/regionlist,/ping
#    server_port: 8080
#    db_name: sealtalk
#    db_user: root
#    db_password: 123456
#    db_host: 127.0.0.1
#    db_port: 3306


#######################

sealtalk-config:
  auth_cookie_name: rong_auth_cookie
  auth_cookie_key: zsyy
  nickname_cookie_name:
  auth_cookie_max_age: 8640000    #  auth_cookie有效期单位秒 8640000=100天
  rongcloud_sms_register_template_id: 3910922   #短信模版
  config_env: dev                 # dev 调试环境 注册环节不发短信，默认验证码9999
  rongcloud_app_key: bmdehs6pbauls
  rongcloud_app_secret: xvQhSJbgYBtwF
  rongcloud_api_url: api-cn.ronghub.com  # rongcloud api_url
  rongcloud_default_portrait_url: http://www.rongcloud.cn/images/icon-57.png        #登录注册默认头像地址
  qiniu_access_key: ctk1VIyQlx5CFr_EQMqrQkF5c1PKGuqC2SNTR749
  qiniu_secret_key: MRuJJ6AcBkFQrgm16ayDtv_4L0M2jsQe-QuMBfiw
  qiniu_bucket_name: dev-sealtalk
  qiniu_bucket_domain: dev.sealtalk.yujianlu.clouddn.com
  yunpian_api_key: 830c36ecb0ef1667e02769e1f33d9942
  yunpian_limited_time: 1     #云片发送验证码限制时间单位 1小时
  yunpian_limited_count: 20   #云片发送验证码次数限制    20次
  n3d_key: 22EdDIauqcQW
  auth_cookie_domain: devtalk.im
  cors_hosts:  web.devtalk.im
  exclude_url: /misc/demo_square,/misc/latest_update, /user/verify_code_yp_t,/misc/client_version,/misc/mobile_version,/user/login,/user/register,/user/reset_password, /user/send_code, /user/send_code_yp,/user/verify_code, /user/verify_code_yp, /user/delete, /user/get_sms_img_code,/user/check_username_available,/user/check_phone_available,/user/regionlist,/ping
  server_port: 8080
  db_name: sealtalk
  db_user: root
  db_password: 123456
  db_host: 127.0.0.1
  db_port: 3306
